name: Sync Leetcode

on:
  workflow_dispatch: # Allows you to run this manually anytime
  schedule:
    - cron: "0 8 * * *" # This runs automatically every day at 8:00 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Explicitly forces write access for the runner script

    steps:
      - name: Sync Solutions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
